---
swagger: '2.0'
info:
  description: Chief Support Systems API
  version: APIVERSION
  title: Chief Support Systems API
  contact:
    name: Simon Skinner
    email: ss@debtpanel.co.uk
host: TEMPLATEHOST.chief.gi
securityDefinitions:
  api_key:
    type: 'apiKey'
    name: 'key'
    in: 'query'
tags:
  - name: Authentication
schemes:
  - https
produces:
  - application/json
paths:
  /auth/login:
    options:
      tags:
        - Authentication
      summary: Login User Options
      operationId: authLoginOptions
      responses:
        '200':
          description: Login
      x-google-backend:
        address: https://staging.api.chief.gi/v1/auth/login
    post:
      tags:
        - Authentication
      summary: Login User
      operationId: authLoginPost
      responses:
        '200':
          description: V1 API
      x-google-backend:
        address: https://staging.api.chief.gi/v1/auth/login
